; Listing generated by Microsoft (R) Optimizing Compiler Version 19.51.36252.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	multstore
EXTRN	mult2:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$multstore DD imagerel $LN4
	DD	imagerel $LN4+22
	DD	imagerel $unwind$multstore
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$multstore DD 020601H
	DD	030023206H
xdata	ENDS
; Function compile flags: /Ogspy
; File D:\programacao\c-intro\csapp\cap3\multstore\mult.c
;	COMDAT multstore
_TEXT	SEGMENT
x$ = 48
y$ = 56
dest$ = 64
multstore PROC						; COMDAT

; 4    : void multstore(long x, long y, long *dest) {

$LN4:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, r8

; 5    : long t = mult2(x, y);

	call	mult2

; 6    : *dest = t;

	mov	DWORD PTR [rbx], eax

; 7    : }

	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
multstore ENDP
_TEXT	ENDS
END
